### ISSUE TITLE
it seems unnormal in the demo when switch between different motion

### ISSUE THREAD

**Issue by visonpon** [xupei0610/ICCGAN#2]
Hi, @xupei0610 ,thanks for sharing this wonderful work, but as in the demo, when switch from walk to run , the leg has some unnormal motion, i wonder if this is the training dataset's problem or this methon's limitation?

**Comment by xupei0610** [comment]
Do you mean the result when you run the following command?

> `python iccgan.py run --ckpt policies/run`

The original motion is from the 5779 to 5850 frames in run2_subject1.bvh of LAFAN1.
https://github.com/ubisoft/ubisoft-laforge-animation-dataset/blob/master/lafan1/lafan1.zip

You may check the original motion for comparison.

**Comment by xupei0610** [comment]
The following is the result I got
![run](https://user-images.githubusercontent.com/876313/176975419-e7c532cc-e7cc-44d6-878d-ce6e041eec7d.gif)

To show the motion more clearly, I slowed the animation by playing at 0.5 speed.

**Comment by visonpon** [comment]
i'm sorry i didn't make it clear.  I notice that in the abstract, you said your method **supports interactive policy switching without requiring any motion generation or motion matching mechanism**, but in the demo when switch between different motion(e,g. from run to walk),there exist some unnormal motion for leg.
Hope you can also share the code of swicth mechanism, thanks~

**Comment by xupei0610** [comment]
We talked about the problem of motion transition quality in the 2nd paragraph of Section 7. Hope that would explain things clearly.

**Comment by visonpon** [comment]
oh,my bad, thanks~
