### ISSUE TITLE
Is_chief

### ISSUE THREAD

**Issue by Yopla38** [xupei0610/ICCGAN#5]
Hello,

I have some problem with training.
When I start 2 workers with command :
Python iccgan.py walk --rank 0 --world_size 8 
Python iccgan.py walk --rank 1 --world_size 8
The training don't start, it's like last issue posted 2 days before (stop in time.wait)
I checked json file path, ok
But if I check in agent_wrapper (iccgan.py), rank is always -1 then is_chief is always False...
Do you know what ?
(When I force rank to 0, it can start 1 worker)

Thanks a lot

**Comment by xupei0610** [comment]
The `world_size` option is the total number of workers that are going to start. If you just launch two worker threads with rank 0 and 1, the program will wait for the other 6 threads to start because you set world_size as 8.

**Comment by Yopla38** [comment]
Oh !!! I'm dumb...
Thanks a lot !
