### ISSUE TITLE
Retargeting

### ISSUE THREAD

**Issue by kuangbixia** [xupei0610/ICCGAN#6]
Hi! Thanks for your wonderful work! 
Can I ask how you retarget the local joint position from the motion data to an arbitrary character model?

**Comment by xupei0610** [comment]
If you are not familiar with retargeting, I would suggest to use software like MotionBuilder instead of writing script yourself.

**Comment by kuangbixia** [comment]
Thanks a lot!

徐霈 (Pei Xu) ***@***.***> 于2022年12月1日周四 11:12写道：
